### ISSUE TITLE
这个在英文字母上是有问题的。

### ISSUE THREAD

**Issue by oneLeaf2012** [EarthMass/ExpandLab#1]
在iPhone 7plus 里填写  With in-depth panel discussions on domestic and global news and current affairs, Today gives you the story behind the headlines. 这个文字的时候，没有显示展开的按钮。如图。。

<img width="311" alt="1837b6fc-330b-42e7-a45f-8500b4af1b8e" src="https://user-images.githubusercontent.com/11239872/27463099-022cb600-57f8-11e7-849d-9f595f2961fb.png">

**Comment by EarthMass** [comment]
已修复
